version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: emulator -list-avds
      - run: echo no | /opt/android/sdk/tools/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-23;google_apis;x86_64'
      - run: emulator -list-avds
#      - run:
#          name: "Got To Project and connectedAndroidTest"
#            command: |
#              cd AndroidDemo
#              ls
#              ./gradlew init
#             ./gradlew connectedAndroidTest
#      - emulator -avd circleci-android21 -no-window
#            background: true
#            parallel: true
        # wait for it to have booted
#      - circle-android wait-for-boot
      # run tests  against the emulator.
#      - AndroidDemo/./gradlew connectedAndroidTest
      # copy the build outputs to artifacts
#      - cp -r AndroidDemo/build/outputs $CIRCLE_ARTIFACTS
      # copy the test results to the test results directory.
#      - cp -r AndroidDemo/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
#      - store_artifacts:
#          path: AndroidDemo/app/build/reports
#          destination: reports
#      - store_test_results:
#          path: AndroidDemo/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
